title: Roundhere.net by Chris Martin
description: A collection of things, by Chris James Martin
author: Chris James Martin
url: "https://roundhere.net"

# Jekyll Configuration
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-feed

# Pagination Settings
pagination:
  enabled: true
  per_page: 10
  permalink: /page/:num/
  sort_field: datetime
  sort_reverse: true

# Collections
collections:
  cheshire:
    output: true
    permalink: /cheshire/:categories/:year/:month/:day/

# Default Page Settings
defaults:
  - scope:
      path: "_cheshire/journal"
      type: "cheshire"
    values:
      layout: "cheshire_journal"
      categories: ["journal"]

# Kramdown Settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Feed Settings
feed:
  icon: /assets/images/favicons/favicon-summer-64.png
  logo: /assets/images/favicons/favicon-summer-512.png
