title: Roundhere.net by Chris Martin
description: A collection of things, by Chris James Martin
author: Chris James Martin
url: "https://roundhere.net"

# Jekyll Configuration
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed

# Pagination Settings
paginate: 10
paginate_path: /journal/page:num/
permalink: /journal/:title/

# Collections
collections:
  cheshire:
    output: true
    permalink: /cheshire/:categories/:year/:month/:day/

# Default Page Settings
defaults:
  - scope:
      path: "_cheshire/journal"
      type: "cheshire"
    values:
      layout: "cheshire_journal"
      categories: ["journal"]

# Kramdown Settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'